# This file is intended to be a file which specifically calls out modules to be published to the Astronomer
# Registry as well as top-level Provider metadata. The file should not be packaged and solely lives in the
# repo. The modules listed should pertain to latest, released version of the repo.

# Python package name.
package-name: snowpark_provider
# The name of the provider to be displayed on the Registry.
display-name: Snowpark Provider
# A description to be displayed on the main Provider page.
description: Snowpark decorator for Apache Airflow
# URL for where user should find the documentation for the Provider. This could be a link to the README,
# an external docs site, etc.
docs_url: https://github.com/astronomer/airflow-provider-sample/blob/main/README.md

# The next sections should be organized by module type (e.g. operators, hooks, functions, decorators, etc.).
#
# Within each section, the ``module`` value should be the path.to.the.module.specifically.
# For example, if the import path for a function is `from snowpark_provider.hooks.sample_hook import SampleHook` then the
# value should be "snowpark_provider.hooks.sample_hook.SampleHook".

hooks:
  - module: snowpark_provider.hooks.snowpark_hook.SnowparkHook

decorators:
  - module: snowpark_provider.decorators.snowpark_decorator.dataframe

